import Darwin
import Foundation

/// Reads the environment the user's terminal would have.
///
/// An app launched from Finder inherits launchd's minimal environment
/// (`PATH=/usr/bin:/bin:/usr/sbin:/sbin`), so it would not find Homebrew in a
/// custom prefix or tools that `mise activate` puts on `PATH`. This runs the
/// user's login shell interactively, as a terminal would, and captures its
/// environment (ARCHITECTURE.md, "Binary resolution", step 2).
///
/// This is the single sanctioned use of a shell's `-c` in MacUp, and it is
/// narrow: the shell is the user's own login shell (validated against
/// `/etc/shells`), the script is a fixed constant with nothing interpolated,
/// and the output is only parsed, never executed. The captured environment is
/// kept in memory and never logged; providers still receive only their
/// allowlisted variables.
public enum LoginShellEnvironment {
    /// Output markers include a per-run nonce and are assembled by `printf`,
    /// so the finished marker never appears in the script text itself (which a
    /// shell may echo or keep in a variable).
    static func beginMarker(_ nonce: String) -> String { "__MACUP_\(nonce)_BEGIN__" }
    static func endMarker(_ nonce: String) -> String { "__MACUP_\(nonce)_END__" }

    /// The user's login shell from the account database, if it is listed in
    /// `/etc/shells`; otherwise `/bin/zsh`.
    public static func userLoginShell(fileSystem: any FileSystem = LocalFileSystem()) -> String {
        let fallback = "/bin/zsh"
        guard let entry = getpwuid(getuid()), let raw = entry.pointee.pw_shell else { return fallback }
        let shell = String(cString: raw)
        let allowed = fileSystem.contents(atPath: "/etc/shells", maximumBytes: 64 * 1024)
            .map { String(decoding: $0, as: UTF8.self).split(whereSeparator: \.isNewline).map(String.init) } ?? []
        guard allowed.contains(shell), fileSystem.isExecutableFile(atPath: shell) else { return fallback }
        return shell
    }

    /// Runs `shell` as an interactive login shell and returns its environment.
    ///
    /// Prompt hooks run first (zsh `precmd_functions`, bash `PROMPT_COMMAND`,
    /// fish `fish_prompt` handlers) because tools such as mise update `PATH`
    /// from them, exactly as they do before each prompt in a terminal.
    public static func capture(
        shell: String,
        runner: any CommandRunning,
        homeDirectory: String,
        baseEnvironment: [String: String],
        timeout: Duration = .seconds(10)
    ) async throws -> [String: String] {
        let nonce = UUID().uuidString.replacingOccurrences(of: "-", with: "")
        guard let script = script(for: shell, nonce: nonce) else {
            throw MacUpError(.unsupported, "MacUp cannot read the environment of \((shell as NSString).lastPathComponent).")
        }
        var environment = EnvironmentPolicy.base.environment(from: baseEnvironment, searchPath: SearchPath.system)
        environment["SHELL"] = shell
        environment["TERM"] = "dumb"
        // Lets people skip slow startup work: `[[ -n $MACUP_RESOLVING_ENVIRONMENT ]] && return`.
        environment["MACUP_RESOLVING_ENVIRONMENT"] = "1"
        let result = try await runner.run(CommandRequest(
            executable: URL(fileURLWithPath: shell),
            arguments: ["-l", "-i", "-c", script],
            environment: environment,
            workingDirectory: URL(fileURLWithPath: homeDirectory, isDirectory: true),
            timeout: timeout,
            effect: .readOnly,
            outputLimit: 4 * 1024 * 1024
        ))
        return try parse(result.standardOutput, nonce: nonce)
    }

    /// The fixed script for a shell family, or `nil` for unsupported shells.
    /// `nonce` is alphanumeric, generated by MacUp; nothing else is inserted.
    static func script(for shell: String, nonce: String) -> String? {
        let dump = "printf '__MACUP_%s_BEGIN__' \(nonce); /usr/bin/env -0; printf '__MACUP_%s_END__' \(nonce)"
        switch (shell as NSString).lastPathComponent {
        case "zsh":
            return "for macup_hook in $precmd_functions; do $macup_hook; done >/dev/null 2>&1; \(dump)"
        case "bash":
            return "[ -n \"${PROMPT_COMMAND:-}\" ] && eval \"$PROMPT_COMMAND\" >/dev/null 2>&1; \(dump)"
        case "sh", "dash", "ksh":
            return dump
        case "fish":
            return "emit fish_prompt >/dev/null 2>&1; \(dump)"
        default:
            return nil
        }
    }

    /// Extracts `NAME=value` pairs between the markers. Anything the shell's
    /// startup files print around them is ignored.
    static func parse(_ output: Data, nonce: String) throws -> [String: String] {
        guard let begin = output.range(of: Data(beginMarker(nonce).utf8)),
              let end = output.range(of: Data(endMarker(nonce).utf8), in: begin.upperBound..<output.endIndex)
        else {
            throw MacUpError.parseFailed("Your login shell did not report its environment.")
        }
        var environment: [String: String] = [:]
        for entry in output[begin.upperBound..<end.lowerBound].split(separator: 0) {
            let text = String(decoding: entry, as: UTF8.self)
            guard let separator = text.firstIndex(of: "=") else { continue }
            let name = String(text[..<separator])
            guard isValidName(name) else { continue }
            environment[name] = String(text[text.index(after: separator)...])
        }
        guard let path = environment["PATH"], !path.isEmpty else {
            throw MacUpError.parseFailed("Your login shell reported no PATH.")
        }
        return environment
    }

    private static func isValidName(_ name: String) -> Bool {
        guard let first = name.unicodeScalars.first, first == "_" || (first.isASCII && CharacterSet.letters.contains(first)) else {
            return false
        }
        return name.unicodeScalars.allSatisfy { $0 == "_" || ($0.isASCII && CharacterSet.alphanumerics.contains($0)) }
    }
}
